# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'PatternMaker' do

pod 'konashi-ios-sdk'
pod 'JTProgressHUD'
pod 'JGProgressHUD'
pod 'FontAwesomeKit'
pod 'Ono'

end

target 'PatternMakerTests' do

end

